In [2]:
import pandas as pd
import numpy as np
champs_df = pd.read_csv("Set13Champions.csv")

In [5]:
# Assuming the first column is the unit name, create the 'image_path' column
champs_df['image_path'] = champs_df.iloc[:, 0].apply(lambda x: f"{x}.png")

# Display the dataframe to verify the new column
champs_df.head()

,unit,cost,health,armor,magic_resist,attack_damage,attack_range,speed_of_attack,dps,skill_name,skill_cost,origin,class,type,image_path,image_path
0,amumu,1,600/1080/1944,35,35,45/68/101,1,0.6,27/41/61,Obsolete Technology,PASSIVE,Automata,Watcher,Magic Tank,NaN,amumu.png
1,darius,1,650/1170/2106,40,40,55/83/124,1,0.7,39/58/87,Decimate,NaN,Conqueror,Watcher,Attack Fighter,NaN,darius.png
2,draven,1,500/900/1620,35,35,45/68/101,1,0.6,27/41/61,Spinning Axes,NaN,Conqueror,Pit Fighter,Attack Carry,NaN,draven.png
3,irelia,1,700/1260/2268,40,40,55/83/124,1,0.7,39/58/87,Defiant Dance,NaN,Rebel,Sentinel,Magic Tank,NaN,irelia.png
4,lux,1,500/900/1620,40,40,55/83/125,1,0.7,39/58/88,Prismatic Barrier,NaN,Academy,Sorceror,Magic Caster,NaN,lux.png

In [6]:
champs_df.to_csv("Set13Champions.csv", index=False)

In [1]:
import pandas as pd

# Load the CSV file
file_path = "Set13Champions.csv"
data = pd.read_csv(file_path)

# Drop the 'type' column
if 'type' in data.columns:
    data = data.drop(columns=['type'])

# Save the updated CSV back to the file
data.to_csv(file_path, index=False)

print(f"'type' column removed and {file_path} updated.")

'type' column removed and Set13Champions.csv updated.

In [2]:
import pandas as pd

# Load the CSV file
file_path = "Set13Champions.csv"
data = pd.read_csv(file_path)

# Fill the 'skill_cost' column with 123
data['skill_cost'] = 123

# Save the updated CSV back to the file
data.to_csv(file_path, index=False)

print(f"'skill_cost' column filled with 123 and {file_path} updated.")

'skill_cost' column filled with 123 and Set13Champions.csv updated.

In [3]:
import pandas as pd

# Load the data
file_path = "Set13Champions.csv"
data = pd.read_csv(file_path)

# Combine 'origin' and 'class' columns into a unified 'traits' column
# Ensure strings are split into lists first, handling multiple values (comma-separated)
data['origin'] = data['origin'].apply(lambda x: [item.strip() for item in x.split(',')] if isinstance(x, str) else [])
data['class'] = data['class'].apply(lambda x: [item.strip() for item in x.split(',')] if isinstance(x, str) else [])

# Create the 'traits' column
data['traits'] = data.apply(lambda row: row['origin'] + row['class'], axis=1)

# Save the updated DataFrame back to the CSV
data.to_csv(file_path, index=False)

print(f"'traits' column added and {file_path} updated.")

'traits' column added and Set13Champions.csv updated.

In [4]:
# Import pandas
import pandas as pd

# Load your dataset
file_path = "Set13Champions.csv"
data = pd.read_csv(file_path)

# Drop columns with all NaN values
data = data.dropna(axis=1, how='all')


# Save the updated DataFrame back to the CSV
data.to_csv(file_path, index=False)

# Display the DataFrame to verify
data.head()

,unit,cost,health,armor,magic_resist,attack_damage,attack_range,speed_of_attack,dps,skill_name,skill_cost,origin,class,image_path,traits
0,amumu,1,600/1080/1944,35,35,45/68/101,1,0.6,27/41/61,Obsolete Technology,123,['Automata'],['Watcher'],amumu.png,"['Automata', 'Watcher']"
1,darius,1,650/1170/2106,40,40,55/83/124,1,0.7,39/58/87,Decimate,123,['Conqueror'],['Watcher'],darius.png,"['Conqueror', 'Watcher']"
2,draven,1,500/900/1620,35,35,45/68/101,1,0.6,27/41/61,Spinning Axes,123,['Conqueror'],['Pit Fighter'],draven.png,"['Conqueror', 'Pit Fighter']"
3,irelia,1,700/1260/2268,40,40,55/83/124,1,0.7,39/58/87,Defiant Dance,123,['Rebel'],['Sentinel'],irelia.png,"['Rebel', 'Sentinel']"
4,lux,1,500/900/1620,40,40,55/83/125,1,0.7,39/58/88,Prismatic Barrier,123,['Academy'],['Sorceror'],lux.png,"['Academy', 'Sorceror']"

In [7]:
# Import pandas
import pandas as pd

# Load your dataset
file_path = "Set13Champions.csv"
data = pd.read_csv(file_path)

In [8]:
data['traits'] = data['traits'].fillna('').apply(lambda x: [t.strip() for t in x.split(',')] if x else [])
data.head()

,unit,cost,health,armor,magic_resist,attack_damage,attack_range,speed_of_attack,dps,skill_name,skill_cost,origin,class,image_path,traits
0,amumu,1.0,600/1080/1944,35.0,35.0,45/68/101,1.0,0.6,27/41/61,Obsolete Technology,123.0,Automata,Watcher,amumu.png,[]
1,darius,1.0,650/1170/2106,40.0,40.0,55/83/124,1.0,0.7,39/58/87,Decimate,123.0,Conqueror,Watcher,darius.png,[]
2,draven,1.0,500/900/1620,35.0,35.0,45/68/101,1.0,0.6,27/41/61,Spinning Axes,123.0,Conqueror,Pit Fighter,draven.png,[]
3,irelia,1.0,700/1260/2268,40.0,40.0,55/83/124,1.0,0.7,39/58/87,Defiant Dance,123.0,Rebel,Sentinel,irelia.png,[]
4,lux,1.0,500/900/1620,40.0,40.0,55/83/125,1.0,0.7,39/58/88,Prismatic Barrier,123.0,Academy,Sorceror,lux.png,[]

In [9]:
import pandas as pd

# Load the data
file_path = "Set13Champions.csv"
data = pd.read_csv(file_path)

# Combine 'origin' and 'class' columns into a unified 'traits' column
# Ensure strings are split into lists first, handling multiple values (comma-separated)
data['origin'] = data['origin'].apply(lambda x: [item.strip() for item in x.split(',')] if isinstance(x, str) else [])
data['class'] = data['class'].apply(lambda x: [item.strip() for item in x.split(',')] if isinstance(x, str) else [])

# Create the 'traits' column
data['traits'] = data.apply(lambda row: row['origin'] + row['class'], axis=1)

# Save the updated DataFrame back to the CSV
data.to_csv(file_path, index=False)

print(f"'traits' column added and {file_path} updated.")

'traits' column added and Set13Champions.csv updated.

In [10]:
data.head()

,unit,cost,health,armor,magic_resist,attack_damage,attack_range,speed_of_attack,dps,skill_name,skill_cost,origin,class,image_path,traits
0,amumu,1.0,600/1080/1944,35.0,35.0,45/68/101,1.0,0.6,27/41/61,Obsolete Technology,123.0,[Automata],[Watcher],amumu.png,"[Automata, Watcher]"
1,darius,1.0,650/1170/2106,40.0,40.0,55/83/124,1.0,0.7,39/58/87,Decimate,123.0,[Conqueror],[Watcher],darius.png,"[Conqueror, Watcher]"
2,draven,1.0,500/900/1620,35.0,35.0,45/68/101,1.0,0.6,27/41/61,Spinning Axes,123.0,[Conqueror],[Pit Fighter],draven.png,"[Conqueror, Pit Fighter]"
3,irelia,1.0,700/1260/2268,40.0,40.0,55/83/124,1.0,0.7,39/58/87,Defiant Dance,123.0,[Rebel],[Sentinel],irelia.png,"[Rebel, Sentinel]"
4,lux,1.0,500/900/1620,40.0,40.0,55/83/125,1.0,0.7,39/58/88,Prismatic Barrier,123.0,[Academy],[Sorceror],lux.png,"[Academy, Sorceror]"

AttributeError: 'list' object has no attribute 'split'